namespace boombang_emulator.src.Enums
{
    public enum AvatarActionsEnum
    {
        WATCH,
        WALK,
        CHAT,
        LITTLE_LAUGHTER,
        BIG_LAUGHTER,
        CRY,
        IN_LOVE,
        SPIT,
        FART,
        SPECIAL,
        FLY,
        GIVE_KISS,
        GIVE_DRINK,
        GIVE_ROSE,
        RECEIVE_KISS,
        RECEIVE_DRINK,
        RECEIVE_ROSE,
        RECEIVE_COCONUT,
        RECEIVE_COCONUT_SNOWBALL,
        RECEIVE_COCONUT_SHOE,
        RECEIVE_COCONUT_CAKE,
        RECEIVE_COCONUT_FLOWERPOT,
        RECEIVE_COCONUT_HONEYCOMB,
        RECEIVE_COCONUT_TRASH,
        RECEIVE_COCONUT_WATERMELON,
        RECEIVE_COCONUT_YUNQUE,
        RECEIVE_COCONUT_PIANO
    }
}
